# Generated by Django 5.1.3 on 2024-11-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
